# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Photorealistic Rendering of Furniture
email: k.jakob.larsson@gmail.com
description: > # this means to ignore newlines until "baseurl:"

  Rendering furniture since 2016.

  This is our diary while working on our bachelors's thesis at Chalmers
  University of Technology.  We are working on three related
  problems in creating photrealistic renders of furniture, with a focus on
  cloth and woven materials.

baseurl: "/Bachelor-work-Furniture" # the subpath of your site, e.g. /blog
url: "http://karljakoblarsson.com/" # the base hostname & protocol for your site

# Build settings
#markdown: kramdown